const db = require('./models/db.js');
const Account= require('./models/UserModel.js');
const Product = require('./models/ProductModel.js');
const Log = require('./models/LoggedModel.js');
const Review = require('./models/ReviewModel.js');
const Transaction = require('./models/TransModel.js');
const History = require('./models/HistoryModel.js');
const Category = require('./models/CategoryModel.js');
const Cart = require('./models/CartModel.js');
const Wishlist = require('./models/WishlistModel.js');
db.connect();
db.deleteMany(Account);
db.deleteMany(Product);
db.deleteMany(Log);
db.deleteMany(Transaction);
db.deleteMany(History);
db.deleteMany(Review);
db.deleteMany(Category);
db.deleteMany(Cart);
db.deleteMany(Wishlist);